version: "3.9"

services:
  app:
    build: .
    container_name: chittchat-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/mydb?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
